### ISSUE TITLE
샘플 코드 감사합니다.

### ISSUE THREAD

**Issue by luckyjun** [jjhyuk/iOS14WidgetExtension#1]
혹시 라이센스가 어떻게 되나요?

소스 참고해서 개발해도 되나요?

**Comment by jjhyuk** [comment]
네 부족한데 참고해주시면 저는 너무 감사하죠!!
저도 한번 해보는 목적이고 간단한 샘플이기에 라이센스는 특별히 없습니다!!
앞으로 명시해둘게요
